print("=== Well hello 👋 Can you save the Island of thurstononia? ===")
print("""We in the battle and you can make 💰💰""")
print()
name =input("What is your Superhero name ")
print()
weapon = input("What is your choice of weapon? ")
print("Good choice 😃")
print()
word = input("What is your favourite word? ")
reward = input("What reward would you like? ")
hero = ("McGrom")
print()
print("Your battle starts when you land on a isolated island full of killer shrimp and their all conquering leader Kamolha, who have taken over")
print()
print("\033[31m",name,"!\033[0m", "is walkng though the jungle, Kamolha and his chief shrimp flip jump out, in order to win you draw your","\033[31m", weapon, "!\033[0m", "and destroy them")
print()
print("Suddenly you are surrounded by shrimp, but think suddenly and shout","!\033[32m", word,"!\033[0m", "and","!\033[32m",hero,"!\033[0m", "appears and all the shrimps are gone, the island is saved and you have your", "!\033[32m",reward,"!\033[0m")